### PR TITLE
Plugins Overhaul [v0]

### PR DESCRIPTION
**Pull request by clebergnu**
This is the Avocado-Virt side of the https://github.com/avocado-framework/avocado/pull/919 pull request.

It implements the changes necessary to have Avocado-Virt plugins as "new style" Avocado plugins.

### CODE REVIEW

**Comment by lmr** [comment]
the problem here is that we are installing a pylint/astroid combination known to not work under python 2.6. I thought I had fixed this.

**Comment by lmr** [comment]
Ah, for a few seconds I thought this was `avocado-vt`. I'll fix the pylint problem.

**Comment by lmr** [comment]
@clebergnu, #71 should contain a fix for the problem you've seen. Let Travis validate it.

**Comment by lmr** [comment]
@clebergnu, problem solved. Please rebase.

**Comment by clebergnu** [comment]
@lmr cool! I'll rebase and send a newer version!

**Comment by clebergnu** [comment]
Closing in favor of #72

**Pull request closed without merging**
