### PR TITLE
Makefile fixes

### PR DESCRIPTION
**Pull request by clebergnu**
Simple Makefile fixes.

### CODE REVIEW

**Comment by ldoktor** [comment]
Is there any get-started documentation about using `make develop` in avocado? I failed to find one.

**Comment by clebergnu** [comment]
@ldoktor there's no `make develop` in Avocado. setuptools provides a *develop* command, which developers can use provided they understand what it does.

**Comment by ldoktor** [comment]
Yep, I'm exploring it now and finally got it working. And from the way it works I think we should remove `make link` and replace it with `make develop` (with arguments) which would do the symlinks + run the `python setup.py develop $args` in each discovered avocado plugin. Then we get the same functionality.

**Comment by ldoktor** [comment]
I can take care of it, I'd just like to know your opinion before wasting time on something completely useless. I'd add DEVELOP_OPTS?="" and run `make develop` for each subdir of the parent dir the same way `make link` worked. That way I can run `DEVELOP_OPTS=--user make develop` which should result in avocado, avocado-vt and avocado-virt deployed using `python setup.py develop --user` and ready to be used.

**Pull request merged**
