### PR TITLE
Make avocado-virt work with the new AvocadoParams [v1]

### PR DESCRIPTION
**Pull request by ldoktor**
This patchset changes the way params are overridden from cmdline. Additionally it changes the flat names and uses key+path instead. See the descriptions for details.

### CODE REVIEW

**Comment by ldoktor** [comment]
@lmr would you please take a look at this one? It fixes the bug when running avocado-virt with yaml file and overriding avocado-virt params on cmdline.

**Comment by clebergnu** [comment]
@ldoktor now I understand more clearly why I was getting this:

```
Exception loading test
Traceback (most recent call last):
  File "/home/cleber/src/avocado/avocado/core/runner.py", line 76, in _run_test
    instance = self.job.test_loader.load_test(test_factory)
  File "/home/cleber/src/avocado/avocado/core/loader.py", line 398, in load_test
    test_instance = test_class(**test_parameters)
  File "/home/cleber/src/avocado/avocado/virt/test.py", line 33, in __init__
    params['virt.qemu.paths.qemu_bin'] = defaults.qemu_bin
TypeError: 'tuple' object does not support item assignment
```

**Comment by clebergnu** [comment]
@ldoktor I tried to `git fetch` from your repo but could not find branch `mux-fix` which is referenced in this PR:

```
$ git branch -rv | grep ldoktor | grep mux-fix
  ldoktor/mux-fixes                             b738645 avocado.core.plugins.multiplexer: Improve variants UI
  ldoktor/mux-fixes2                            b88497a avocado.core.tree: Remove useless code
```

And the following link gives a 404:

https://github.com/ldoktor/avocado/tree/mux-fix

Any ideas?

**Comment by clebergnu** [comment]
@ldoktor never mind about the (now deleted) comment on a missing branch. Stupid me.

**Comment by ldoktor** [comment]
@clebergnu oh, I talked about this on last sprint meeting ;-) https://trello.com/c/pjv3YZ0F/388-bug-avocado-virt-doesn-t-work-with-the-latest-avocadoparams anyway this patch should fix it so I hope to get it merged before the end of this sprint.

**Comment by clebergnu** [comment]
@ldoktor yep. I'm reviewing it right now.

**Pull request closed without merging**
